name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18

      - run: yarn --frozen-lockfile

      - name: Type check scripts
        run: yarn build

      - name: Lint presets
        run: yarn lint

      - name: Basic config validation
        run: yarn test:basic

      - name: Renovate dry run with all configs
        run: yarn test:full
        env:
          TOKEN: ${{ secrets.TOKEN_GITHUB_READ }}
