name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: yarn

      - name: update preset repo paths in configs
        run: yarn fix-repo-refs

      - name: test configs
        run: yarn test

      - name: commit and push
        run: |
          git commit -a -m 'Update README.md'
          git push origin main
