name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: yarn --frozen-lockfile

      - name: Type check scripts
        run: yarn build

      - name: Basic config validation
        run: yarn test:basic
        env:
          CI: true

      - name: Renovate dry run with all configs
        run: yarn test:full
        env:
          CI: true
          GITHUB_REF: $(github.ref)
          GITHUB_REPOSITORY: $(github.repository)
          TOKEN: $(secrets.TOKEN_GITHUB_READ)
