name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: yarn

      - name: install Renovate (latest)
        run: yarn add -D renovate

      - name: update preset repo paths in configs
        run: node ./scripts/fixRepoRefs.js

      - name: test configs
        run: |
          for config in *.json5; do
            echo "Testing $config with content:"
            cat $config
            echo
            RENOVATE_CONFIG_FILE=$config yarn renovate-config-validator $config
            if [[ $? -ne 0 ]]; then
              echo "::error file=$config::Invalid config file"
            fi
            echo
          done
